accounts/urls.py
from django.urls import path
from . import views
app_name="accounts"

urlpatterns=[
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

django_pjt5/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('accounts/', include('accounts.urls')),
]

movies/urls.py
from django.urls import path
from . import views
app_name = "movies"

urlpatterns = [
    path('', views.movie_list, name ='movie_list'),
    path('<int:movie_pk>/detail/', views.movie_detail, name ='movie_detail'),
    path('<int:movie_pk>/like/', views.movie_like, name ='movie_like'),
    path('recommend/', views.recommend, name ='recommend'),


]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.


class User(AbstractUser):
    pass

movies/models.py
from django.db import models
from django.contrib.auth import get_user_model

# Create your models here.
class Genre(models.Model):
    name = models.CharField(max_length=255)


class Movie(models.Model):
    title = models.CharField( max_length=255)
    original_title = models.CharField( max_length=255)
    release_date = models.DateField(auto_now=False, auto_now_add=False)
    popularity = models.FloatField()
    vote_count = models.IntegerField()
    vote_average = models.FloatField()
    adult = models.BooleanField()
    overview = models.TextField()
    original_language = models.CharField( max_length=255)
    poster_path = models.CharField( max_length=255)
    backdrop_path = models.CharField( max_length=255)
    genres = models.ManyToManyField(Genre, related_name='genre_movies')
    like_users = models.ManyToManyField(get_user_model(), related_name="like_movies")

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields= ['username']

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import login as auth_login
from django.contrib.auth.forms import AuthenticationForm
from .forms import CustomUserCreationForm


# Create your views here.
def signup(request):
    if request.user.is_authenticated:
        return redirect('movies:movie_list')

    if request.method=="POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('movies:movie_list')
    else:
        form = CustomUserCreationForm()
    context={
        'form' : form
    }
    
    return render(request, 'accounts/form.html', context)


def login(request):
    if request.user.is_authenticated:
        return redirect('movies:movie_list')

    if request.method=="POST":
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect(request.GET.get('next') or 'movies:movie_list')
    else:
        form = AuthenticationForm()
    context={
        'form' : form
    }
    return render(request, 'accounts/form.html', context)


def logout(request):
    auth_logout(request)
    return redirect('movies:movie_list')

movies/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from rest_framework.decorators import api_view
from django.http import JsonResponse
from rest_framework.response import Response
from django.db.models import Count
from .models import Movie, Genre
from datetime import datetime
from .serializers import GenreSerializer,MovieSerializer

# Create your views here.

def movie_list(request):
    movies = Movie.objects.all().order_by('-vote_count')

    paginator = Paginator(movies,12)

    page_number = request.GET.get('page')

    page_obj = paginator.get_page(page_number)

    context={
        'movies' : movies,
        'page_obj' : page_obj
    }

    return render(request, 'movies/movie_list.html', context)

@login_required
def movie_detail(request, movie_pk):
    movie = get_object_or_404(Movie, pk= movie_pk)
    context={
        'movie':movie
    }
    return render(request, 'movies/detail.html', context)


def movie_like(request, movie_pk):
    user = request.user
    movie = get_object_or_404(Movie, pk= movie_pk)
    flag = True

    if movie.like_users.filter(pk=user.pk).exists():
        movie.like_users.remove(user)
        flag = False
    else:
        movie.like_users.add(user)
        flag =True
    message = '성공'
    count = movie.like_users.count()

    data={
        'message' : message,
        'flag' :flag,
        'count' : count
    }
    return JsonResponse(data)



@api_view(['GET'])
def recommend(request):
    if len(request.user.like_movies.values('genres')) ==0 :
    ## 다른거 좋아요 누른 적 있으면 같은 장르.
        temp = datetime.now().second % 19
        print(temp)
        arr= [10770,10752,10751,10749,10402,9648,878,99,80,53,37,36,35,28,27,18,16,14,12]
        genre = get_object_or_404(Genre, pk=arr[temp])
    else:
        genre_id = request.user.like_movies.values('genres').annotate(count=Count('genres'))[0].get('genres')
        genre = get_object_or_404(Genre, pk = genre_id)
    movies =Movie.objects.filter(genres=genre)
    serializer = MovieSerializer(movies, many =True)
    # data={
    #     'date' : date,
    #     'movie': serializer.data
    # }
    return Response(serializer.data)

accounts/templates/accounts/form.html
{% extends 'base.html' %}
{% load bootstrap4 %}


<div class="row">
{% block content %}
    <form action="" method ="POST">
        {% csrf_token %}
        {% bootstrap_form form%}
        <button>확인</button>
    </form>
{% endblock content %}
</div>

movies/templates/movies/detail.html
{% extends 'base.html' %}


{% block content %}
<h1>Detail</h1>
{{movie.title}}

{% if request.user in movie.like_users.all %}
    <i class="fas fa-heart fa-lg like" style="color:crimson" data-article-id="{{movie.id}}"></i>
{% else %}
    <i class="fas fa-heart fa-lg like" style="color:black" data-article-id="{{movie.id}}"></i>
{% endif %}
    <span id="like-count-{{movie.pk}}">{{ movie.like_users.all|length }}</span> 명이 이 영화를 좋아합니다.
{% endblock content %}


{% block script %}
<script>
    document.querySelectorAll('.like').forEach(item=>{
        item.addEventListener('click', event=>{
            const movieId = event.target.dataset.articleId
            axios.get(`/movies/${movieId}/like/`)
                .then(res=>{
                    const count = res.data.count
                    const flag = res.data.flag 
                    if(flag){
                        document.querySelector('.like').setAttribute('style', 'color:crimson')
                    }else{
                        document.querySelector('.like').setAttribute('style', 'color:black')

                    }
                    document.querySelector(`#like-count-${movieId}`).innerText = count
                })

        })


    })



</script>


{% endblock script %}

movies/templates/movies/movie_list.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load bootstrap_pagination %}


{% block content %}
    <button id = "recommendButton">추천좀 </button>
    <ul id="recommendMovie">

    </ul>
    <div class="row mt-5">

 
    
    
    {% for movie in page_obj %}
        <div class="card" style="width: 9rem;" >
        <img src="https://image.tmdb.org/t/p/w342/{{movie.poster_path}}" class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title">{{movie.title}}</h5>
            <p class="card-text">
                {% for genre in movie.genres.all  %}
                    {{genre.name}},
                {% endfor %}
            
            </p>
            <a href="{% url 'movies:movie_detail' movie.pk %}" class="btn btn-primary">상세 페이지</a>
            <p>{{ movie.like_users.all|length }} 명이 좋아 합니다.</p>
        </div>
        </div>

    {% endfor %}
    

    </div>
    {% bootstrap_paginate page_obj range=5 show_prev_next="false" show_first_last="true" %}

    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>

{% endblock content %}

{% block script %}
<script>
    document.querySelector('#recommendButton').addEventListener('click',event=>{
        axios.get('/movies/recommend/')
            .then(res=>{
                const space = document.querySelector('#recommendMovie')
                const display = document.querySelector('.recommendMovies')
                if(!display){
                for(i=0; i<10; i++){
                const pTag = document.createElement('li')
                pTag.innerText= res.data[i].title
                pTag.setAttribute('class', 'recommendMovies')
                space.appendChild(pTag)
                }
                }else{
                    const temp = document.querySelectorAll('.recommendMovies')
                    for(i=0; i<res.data.length;i++){
                        if(temp[i]){
                            temp[i].innerText=res.data[i].title
                        }else{
                            break
                        }
                    }
                }
            })
    })
</script>

{% endblock script %}

templates/base.html
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>NC 우승</title>
    {% bootstrap_css %}
    <script src="https://kit.fontawesome.com/7c8f649667.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'movies:movie_list'%}">무비무비</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
            aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-item nav-link active" href="{% url 'movies:movie_list'%}">Home</a>
                {% if request.user.is_authenticated %}
                    welcome {{request.user.username}}
                <a class="nav-item nav-link" href="{% url 'accounts:logout' %}">로그아웃</a>
                {% else %}
                <a class="nav-item nav-link" href="{% url 'accounts:signup' %}">회원가입</a>
                <a class="nav-item nav-link" href="{% url 'accounts:login' %}">로그인</a>
                {% endif %}
            </div>
        </div>
    </nav>




    <div class='container'>
    {% block content %}
    {% endblock content %}
    </div>


    {% block script %}
    {% endblock script %}
{% bootstrap_javascript jquery='full' %}
</body>
</html>